/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Manager;
import DBconnection.manager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Gimhan
 */
public class ProfilePanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfilePanel
     */
    public ProfilePanel() {
        initComponents();
        setdata();
    }
    public void setdata(){
       try {
            
            manager obj=new manager();
            txt_fname.setText(obj.getfname());
            txt_lname.setText(obj.getlname());
            txt_email.setText(obj.getEmail());
            txt_nic.setText(obj.getNIC());
            txt_tp.setText("0"+obj.getTp()); 
            lbl_errorpwd.setText(""); 
            lbl_error.setText(""); 
        } catch (Exception ex) {
            Logger.getLogger(ProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_lname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_nic = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_tp = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_newpwd_c = new javax.swing.JPasswordField();
        checkbox_pwd_change = new javax.swing.JCheckBox();
        btn_change_pwd = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_oldpwd = new javax.swing.JPasswordField();
        txt_newpwd = new javax.swing.JPasswordField();
        btn_changeprofiledata = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        lbl_error = new javax.swing.JLabel();
        lbl_errorpwd = new javax.swing.JLabel();
        lbl_background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(173, 85, 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 1170, 30));

        jPanel2.setBackground(new java.awt.Color(173, 85, 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("My Profile");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Last Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        txt_lname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_lname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_lnameMouseClicked(evt);
            }
        });
        add(txt_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 170, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("First Name");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        txt_fname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_fname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_fnameMouseClicked(evt);
            }
        });
        add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 170, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Email");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_emailMouseClicked(evt);
            }
        });
        add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 260, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("NIC");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        txt_nic.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_nic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_nicMouseClicked(evt);
            }
        });
        add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 170, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Mobile Number");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        txt_tp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_tp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_tpMouseClicked(evt);
            }
        });
        add(txt_tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 170, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("New Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Confirm New Password");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txt_newpwd_c.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_newpwd_c.setEnabled(false);
        txt_newpwd_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_newpwd_cMouseClicked(evt);
            }
        });
        jPanel1.add(txt_newpwd_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 130, -1));

        checkbox_pwd_change.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkbox_pwd_change.setText("Change Password");
        checkbox_pwd_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_pwd_changeActionPerformed(evt);
            }
        });
        jPanel1.add(checkbox_pwd_change, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        btn_change_pwd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_change_pwd.setText("Change");
        btn_change_pwd.setEnabled(false);
        btn_change_pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_change_pwdActionPerformed(evt);
            }
        });
        jPanel1.add(btn_change_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 130, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Old Password");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txt_oldpwd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_oldpwd.setEnabled(false);
        txt_oldpwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_oldpwdMouseClicked(evt);
            }
        });
        txt_oldpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_oldpwdActionPerformed(evt);
            }
        });
        jPanel1.add(txt_oldpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 130, -1));

        txt_newpwd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_newpwd.setEnabled(false);
        txt_newpwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_newpwdMouseClicked(evt);
            }
        });
        jPanel1.add(txt_newpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 130, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 380, 280));

        btn_changeprofiledata.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_changeprofiledata.setText("Save Changes");
        btn_changeprofiledata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changeprofiledataActionPerformed(evt);
            }
        });
        add(btn_changeprofiledata, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 580, 230, -1));

        btn_reset.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 580, 110, -1));

        lbl_error.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_error.setForeground(new java.awt.Color(255, 51, 51));
        lbl_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_error.setText("lbl_error");
        add(lbl_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 460, -1));

        lbl_errorpwd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_errorpwd.setForeground(new java.awt.Color(255, 51, 51));
        lbl_errorpwd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_errorpwd.setText("lbl_errorpwd");
        add(lbl_errorpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 460, -1));
        add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 770));
    }// </editor-fold>//GEN-END:initComponents

    private void checkbox_pwd_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_pwd_changeActionPerformed
        boolean check = checkbox_pwd_change.getModel().isSelected();
        txt_oldpwd.setEnabled(check);
        txt_newpwd_c.setEnabled(check);
        txt_newpwd.setEnabled(check);
        btn_change_pwd.setEnabled(check);
        txt_oldpwd.setText("");
        txt_newpwd.setText("");
        txt_newpwd_c.setText("");
        lbl_errorpwd.setText("");
    }//GEN-LAST:event_checkbox_pwd_changeActionPerformed

    private void btn_change_pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_change_pwdActionPerformed
        try {
            manager obj1=new manager();
            if(txt_oldpwd.getText().equals("")){
                lbl_errorpwd.setText("Please enter the old password");
                txt_oldpwd.requestFocus();
            }
            else if(txt_newpwd.getText().equals("")){
                lbl_errorpwd.setText("Please enter the new password");
                txt_newpwd.requestFocus();
            }
            else if(txt_newpwd_c.getText().equals("")){
                lbl_errorpwd.setText("Please Confirm your password");
                txt_newpwd_c.requestFocus();
            }
            else if(!txt_newpwd_c.getText().equals(txt_newpwd.getText())){
                lbl_errorpwd.setText("Those passwords didn’t match. Try again.");
                txt_newpwd_c.requestFocus();
                txt_newpwd_c.setText("");
            }
            else if(txt_newpwd.getText().length()<6){
                lbl_errorpwd.setText("Use 6 characters or more for your password");
                txt_newpwd.requestFocus();
            }
            else if(!obj1.checkOldPwd(txt_oldpwd.getText())){
                lbl_errorpwd.setText("Old passward is incorrect");
                txt_oldpwd.requestFocus();
            }
            else{
                obj1.setPwd(txt_newpwd.getText());
                checkbox_pwd_change.setSelected(false);
                boolean check = checkbox_pwd_change.getModel().isSelected();
                txt_oldpwd.setEnabled(check);
                txt_newpwd_c.setEnabled(check);
                txt_newpwd.setEnabled(check);
                btn_change_pwd.setEnabled(check);
                txt_oldpwd.setText("");
                txt_newpwd.setText("");
                txt_newpwd_c.setText("");
                lbl_errorpwd.setText("");
                JOptionPane.showMessageDialog(new JFrame(), "Passward changed",
                    "Imformation", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(ProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btn_change_pwdActionPerformed

    private void txt_oldpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_oldpwdActionPerformed

    }//GEN-LAST:event_txt_oldpwdActionPerformed

    private void txt_oldpwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_oldpwdMouseClicked
        lbl_errorpwd.setText("");
    }//GEN-LAST:event_txt_oldpwdMouseClicked

    private void txt_newpwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_newpwdMouseClicked
        lbl_errorpwd.setText("");
    }//GEN-LAST:event_txt_newpwdMouseClicked

    private void txt_newpwd_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_newpwd_cMouseClicked
        lbl_errorpwd.setText("");
    }//GEN-LAST:event_txt_newpwd_cMouseClicked

    private void btn_changeprofiledataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changeprofiledataActionPerformed
        lbl_error.setVisible(false);
        if(txt_fname.getText().isEmpty()){
            lbl_error.setText("Please enter the first name");
            txt_fname.requestFocus();
        }
        else if(txt_fname.getText().length()<=2 || txt_fname.getText().length()>=15){
            lbl_error.setText("First name length should between 2 to 15");
            txt_fname.requestFocus();
        }
        else if(!txt_fname.getText().matches("[a-zA-Z]+")){//need to do validations
            lbl_error.setText("First name can have only english letters");
            txt_fname.requestFocus();
        }
        else if(txt_lname.getText().isEmpty()){
            lbl_error.setText("Please enter the last name");
            txt_lname.requestFocus();
        }
        else if(txt_lname.getText().length()<=2 || txt_fname.getText().length()>=15){
            lbl_error.setText("Please enter a valid last name");
            txt_lname.requestFocus();
        }
        else if(!txt_lname.getText().matches("[a-zA-Z]+")){
            lbl_error.setText("Last name can have only english letters");
            txt_lname.requestFocus();
        }
        else if(!txt_email.getText().matches("[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}")){
            lbl_error.setText("Invalid email format");
            lbl_error.setVisible(true);
            txt_email.requestFocus();
        }
        else if(txt_email.getText().length()<=2 || txt_email.getText().length() > 50){
            lbl_error.setText("Invalid email length Please enter a valid email address.");
            lbl_error.setVisible(true);
            txt_email.requestFocus();
        }
        else if (txt_nic.getText().length() != 10 && txt_nic.getText().length() != 12) {
            lbl_error.setText("Invalid NIC length Please enter a valid email address.");
            lbl_error.setVisible(true);
            txt_nic.requestFocus();
        }
        else if (!txt_nic.getText().matches("^\\d{9}[vVxX]|[12]\\d{11}$")) {
            lbl_error.setText("Sri Lankan NIC numbers should follow ...");
            lbl_error.setVisible(true);
            txt_nic.requestFocus();
        }
        else if (String.valueOf(txt_tp.getText()).charAt(0) != '0') {//need to start with 0
            lbl_error.setText("Phone number must 07XXXXXXXX");
            lbl_error.setVisible(true);
        }
        else if(txt_tp.getText().matches("[0-9]+")==false)//if not only numbers
        {
            lbl_error.setText("Please enter a correct moblie number");
            lbl_error.setVisible(true);
        }
        else if(txt_tp.getText().length()!=10)//if more than 10 digits
        {
            lbl_error.setText("Please enter a correct moblie number");
            lbl_error.setVisible(true);
        }
        else{
            try {
                manager obj2=new manager();
                obj2.setManagerDetails(txt_fname.getText(),txt_lname.getText(),txt_email.getText(),txt_tp.getText(),txt_nic.getText());
                JOptionPane.showMessageDialog(new JFrame(), "Details successfully changed",
                    "Imformation", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                Logger.getLogger(ProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_changeprofiledataActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        setdata();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void txt_nicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nicMouseClicked
        lbl_error.setVisible(false);
    }//GEN-LAST:event_txt_nicMouseClicked

    private void txt_fnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_fnameMouseClicked
        lbl_error.setVisible(false);
    }//GEN-LAST:event_txt_fnameMouseClicked

    private void txt_lnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_lnameMouseClicked
        lbl_error.setVisible(false);
    }//GEN-LAST:event_txt_lnameMouseClicked

    private void txt_emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_emailMouseClicked
        lbl_error.setVisible(false);
    }//GEN-LAST:event_txt_emailMouseClicked

    private void txt_tpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_tpMouseClicked
        lbl_error.setVisible(false);
    }//GEN-LAST:event_txt_tpMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_change_pwd;
    private javax.swing.JButton btn_changeprofiledata;
    private javax.swing.JButton btn_reset;
    private javax.swing.JCheckBox checkbox_pwd_change;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_errorpwd;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JPasswordField txt_newpwd;
    private javax.swing.JPasswordField txt_newpwd_c;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JPasswordField txt_oldpwd;
    private javax.swing.JTextField txt_tp;
    // End of variables declaration//GEN-END:variables
}
