/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Manager;
import DBconnection.manager;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Gimhan
 */
public class ProfilePanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfilePanel
     */
    public ProfilePanel() {
        try {
            initComponents();
            manager obj=new manager();
            lbl_fname.setText(obj.getfname());
            lbl_lname.setText(obj.getlname());
            lbl_email.setText(obj.getEmail());
            lbl_nic.setText(obj.getNIC());
            lbl_tp.setText(obj.getTp());           
        } catch (Exception ex) {
            Logger.getLogger(ProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_lname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lbl_fname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbl_email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbl_nic = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lbl_tp = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_newpwd_c = new javax.swing.JPasswordField();
        checkbox_pwd_change = new javax.swing.JCheckBox();
        btn_change_pwd = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_oldpwd = new javax.swing.JPasswordField();
        txt_newpwd = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        lbl_background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(173, 85, 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 1170, 30));

        jPanel2.setBackground(new java.awt.Color(173, 85, 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("My Profile");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Last Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        lbl_lname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(lbl_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 170, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("First Name");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        lbl_fname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(lbl_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 170, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Email");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        lbl_email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 260, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("NIC");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        lbl_nic.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(lbl_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 170, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Mobile Number");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        lbl_tp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(lbl_tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 170, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("New Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Confirm New Password");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txt_newpwd_c.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_newpwd_c.setEnabled(false);
        jPanel1.add(txt_newpwd_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 130, -1));

        checkbox_pwd_change.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkbox_pwd_change.setText("Change Password");
        checkbox_pwd_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_pwd_changeActionPerformed(evt);
            }
        });
        jPanel1.add(checkbox_pwd_change, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        btn_change_pwd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_change_pwd.setText("Change");
        btn_change_pwd.setEnabled(false);
        btn_change_pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_change_pwdActionPerformed(evt);
            }
        });
        jPanel1.add(btn_change_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 130, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Old Password");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txt_oldpwd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_oldpwd.setEnabled(false);
        jPanel1.add(txt_oldpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 130, -1));

        txt_newpwd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_newpwd.setEnabled(false);
        jPanel1.add(txt_newpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 130, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 380, 280));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Save Changes");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, 230, -1));
        add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 770));
    }// </editor-fold>//GEN-END:initComponents

    private void checkbox_pwd_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_pwd_changeActionPerformed
        // TODO add your handling code here:
        boolean check = checkbox_pwd_change.getModel().isSelected();
        txt_oldpwd.setEnabled(check);
        txt_newpwd_c.setEnabled(check);
        txt_newpwd.setEnabled(check);
        btn_change_pwd.setEnabled(check);
    }//GEN-LAST:event_checkbox_pwd_changeActionPerformed

    private void btn_change_pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_change_pwdActionPerformed
       checkbox_pwd_change.setSelected(false);
       boolean check = checkbox_pwd_change.getModel().isSelected();
        txt_oldpwd.setEnabled(check);
        txt_newpwd_c.setEnabled(check);
        txt_newpwd.setEnabled(check);
        btn_change_pwd.setEnabled(check);
    }//GEN-LAST:event_btn_change_pwdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_change_pwd;
    private javax.swing.JCheckBox checkbox_pwd_change;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JTextField lbl_email;
    private javax.swing.JTextField lbl_fname;
    private javax.swing.JTextField lbl_lname;
    private javax.swing.JTextField lbl_nic;
    private javax.swing.JTextField lbl_tp;
    private javax.swing.JPasswordField txt_newpwd;
    private javax.swing.JPasswordField txt_newpwd_c;
    private javax.swing.JPasswordField txt_oldpwd;
    // End of variables declaration//GEN-END:variables
}
