/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Manager;

import DBconnection.Connect;
import DBconnection.Customer;
import DBconnection.Emp;
import DBconnection.LoyaltyCard;
import DBconnection.cashier;
import DBconnection.getDate;
import java.awt.Component;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Gimhan
 */
public class SDDetailsPanel extends javax.swing.JPanel {

    /**
     * Creates new form sdDetailsPanel
     */
    public SDDetailsPanel() {
        initComponents();
        Panel_AddEditStuff.setVisible(false);
        panel_main.setVisible(true);
        lbl_Error.setVisible(false);
        btn_edit.setEnabled(false);
        lbl_error.setVisible(false);
        lbl_errorpwd.setVisible(false);
        viewALL();
        jTable1.getTableHeader().setFont(new Font("SansSerif", Font.PLAIN, 15));
        jComboBox_stufftype.setFont(new Font("SansSerif", Font.PLAIN, 15));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panel_main = new javax.swing.JPanel();
        lbl_empty = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_searchtitle = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        lbl_Error = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rdo_stuff = new javax.swing.JRadioButton();
        rdo_customer = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        Panel_AddEditStuff = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_tp = new javax.swing.JTextField();
        txt_nic = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        txt_fname = new javax.swing.JTextField();
        lbl_error = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_newpwd_c = new javax.swing.JPasswordField();
        checkbox_pwd_change = new javax.swing.JCheckBox();
        btn_change_pwd = new javax.swing.JButton();
        txt_newpwd = new javax.swing.JPasswordField();
        lbl_errorpwd = new javax.swing.JLabel();
        btn_reset = new javax.swing.JButton();
        btn_changeSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_empID = new javax.swing.JTextField();
        btn_close = new javax.swing.JButton();
        jComboBox_stufftype = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(173, 85, 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 1170, 30));

        jPanel1.setBackground(new java.awt.Color(173, 85, 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 30));

        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_empty.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_empty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_empty.setText("No results");
        panel_main.add(lbl_empty, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 310, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Customer/Staff Details");
        panel_main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 10, -1, -1));

        lbl_searchtitle.setText("Search by Customer Telephone Number");
        panel_main.add(lbl_searchtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 300, -1));

        btn_search.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        panel_main.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 110, 40));

        txt_search.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_searchMouseClicked(evt);
            }
        });
        panel_main.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 220, 40));

        lbl_Error.setForeground(new java.awt.Color(255, 0, 0));
        lbl_Error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Error.setText("Error msg");
        panel_main.add(lbl_Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 710, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(29);
        jScrollPane1.setViewportView(jTable1);

        panel_main.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 960, 420));

        buttonGroup1.add(rdo_stuff);
        rdo_stuff.setText("Staff Details");
        rdo_stuff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_stuffActionPerformed(evt);
            }
        });
        panel_main.add(rdo_stuff, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        buttonGroup1.add(rdo_customer);
        rdo_customer.setSelected(true);
        rdo_customer.setText("Customer Details");
        rdo_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_customerActionPerformed(evt);
            }
        });
        panel_main.add(rdo_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jButton5.setText("View All");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel_main.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 240, 100, 40));

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        panel_main.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 300, 100, 40));

        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        panel_main.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 470, 110, 40));

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        panel_main.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 520, 110, 40));

        btn_remove.setText("Remove");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });
        panel_main.add(btn_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 570, 110, 40));

        add(panel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1140, 640));

        Panel_AddEditStuff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Employee type");
        Panel_AddEditStuff.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Last Name");
        Panel_AddEditStuff.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 336, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Email");
        Panel_AddEditStuff.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("NIC");
        Panel_AddEditStuff.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Mobile Number");
        Panel_AddEditStuff.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, -1, 20));

        txt_tp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Panel_AddEditStuff.add(txt_tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 170, 33));

        txt_nic.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Panel_AddEditStuff.add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 170, 35));

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Panel_AddEditStuff.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 383, 310, 35));

        txt_lname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Panel_AddEditStuff.add(txt_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 170, 35));

        txt_fname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Panel_AddEditStuff.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 170, 35));

        lbl_error.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_error.setForeground(new java.awt.Color(255, 51, 51));
        lbl_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_error.setText("lbl_error");
        Panel_AddEditStuff.add(lbl_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 700, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("New Password");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Confirm New Password");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txt_newpwd_c.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_newpwd_c.setEnabled(false);
        txt_newpwd_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_newpwd_cMouseClicked(evt);
            }
        });
        jPanel3.add(txt_newpwd_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 130, -1));

        checkbox_pwd_change.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkbox_pwd_change.setText("Change Password");
        checkbox_pwd_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_pwd_changeActionPerformed(evt);
            }
        });
        jPanel3.add(checkbox_pwd_change, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        btn_change_pwd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_change_pwd.setText("Change");
        btn_change_pwd.setEnabled(false);
        btn_change_pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_change_pwdActionPerformed(evt);
            }
        });
        jPanel3.add(btn_change_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 130, 40));

        txt_newpwd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_newpwd.setEnabled(false);
        txt_newpwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_newpwdMouseClicked(evt);
            }
        });
        jPanel3.add(txt_newpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 130, -1));

        Panel_AddEditStuff.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 380, 220));

        lbl_errorpwd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_errorpwd.setForeground(new java.awt.Color(255, 51, 51));
        lbl_errorpwd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_errorpwd.setText("lbl_errorpwd");
        Panel_AddEditStuff.add(lbl_errorpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 460, -1));

        btn_reset.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        Panel_AddEditStuff.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 110, 40));

        btn_changeSave.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_changeSave.setText("Save Changes");
        btn_changeSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changeSaveActionPerformed(evt);
            }
        });
        Panel_AddEditStuff.add(btn_changeSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 490, 150, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add New Staff Member");
        Panel_AddEditStuff.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 480, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Employee ID");
        Panel_AddEditStuff.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        txt_empID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_empID.setEnabled(false);
        Panel_AddEditStuff.add(txt_empID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 170, 33));

        btn_close.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        Panel_AddEditStuff.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 150, 40));

        jComboBox_stufftype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cashier", "Chef" }));
        jComboBox_stufftype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_stufftypeActionPerformed(evt);
            }
        });
        Panel_AddEditStuff.add(jComboBox_stufftype, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 170, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("First Name");
        Panel_AddEditStuff.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 275, -1, 20));

        add(Panel_AddEditStuff, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1130, 680));
    }// </editor-fold>//GEN-END:initComponents

    private void viewALL(){
        try{
            lbl_Error.setVisible(false);
            clearTable();
            Connect obj = new Connect();
            Connection c = obj.getConnection();//Establish the connection
            cashier obj2=new cashier();
             //int q=1;System.out.println(q++); <- tester
                getDate obj1 =new getDate();
                String date=obj1.dateOnly();
                Statement stmt = c.createStatement();//Prepare statement
                ResultSet rs;
                //customer data
                if(rdo_customer.isSelected()){
                    //Change table header
                    JTableHeader th = jTable1.getTableHeader();
                    TableColumnModel tcm = th.getColumnModel();
                    TableColumn tc = tcm.getColumn(0);
                    tc.setHeaderValue( "Customer ID" );
                    th.repaint();
                    tc = tcm.getColumn(1);
                    tc.setHeaderValue( "Customer Name" );
                    th.repaint();
                    tc = tcm.getColumn(2);
                    tc.setHeaderValue( "Mobile number" );
                    th.repaint();
                    tc = tcm.getColumn(3);
                    tc.setHeaderValue( "Loyalty points");
                    th.repaint();
                    tc = tcm.getColumn(4);
                    tc.setHeaderValue( "Loyalty card" );
                    th.repaint();
                    //tc = tcm.getColumn(5);
                    //tc.setHeaderValue( "Email" );
                    //th.repaint();
                    //
                    rs = stmt.executeQuery("select * FROM CUSTOMER WHERE CUSTOMER_ID !='CS000'");
                    while(rs.next()){
                        String cID=rs.getString("CUSTOMER_ID");
                        String fname=rs.getString("F_NAME");
                        String lname=rs.getString("L_NAME");
                        String tp=rs.getString("MOBILE_NUMBER");
                        String email=rs.getString("Email");
                        String points=rs.getString("POINTS");
                        String request="No";
                        if(rs.getInt("REQUEST")==1)
                            request="Requested";
                        else if(rs.getInt("REQUEST")==2)
                            request="Have";
                        String tbData[]={cID,fname+" "+lname,tp,points,request,email};
                        DefaultTableModel tblModel =(DefaultTableModel)jTable1.getModel(); 
                        tblModel.addRow(tbData);
                    }
                    btn_add.setEnabled(false); 
                }
                else{
                    //Change table header
                    JTableHeader th = jTable1.getTableHeader();
                    TableColumnModel tcm = th.getColumnModel();
                    TableColumn tc = tcm.getColumn(0);
                    tc.setHeaderValue( "Employee ID" );
                    th.repaint();
                    tc = tcm.getColumn(1);
                    tc.setHeaderValue( "Employee Name" );
                    th.repaint();
                    tc = tcm.getColumn(2);
                    tc.setHeaderValue( "Employee type" );
                    th.repaint();
                    tc = tcm.getColumn(3);
                    tc.setHeaderValue( "Mobile number");
                    th.repaint();
                    tc = tcm.getColumn(4);
                    tc.setHeaderValue( "NIC" );
                    th.repaint();
                    //tc = tcm.getColumn(5);
                    //tc.setHeaderValue( "Email" );
                    //th.repaint();
                    //
                    rs = stmt.executeQuery("select * FROM EMPLOYEE WHERE EMP_ID != 'EM001'");
                    while(rs.next()){
                        String cID=rs.getString("EMP_ID");
                        String name=rs.getString("F_NAME")+" "+rs.getString("L_NAME");
                        String tp=rs.getString("MOBILE_NUMBER");
                        String email=rs.getString("Email");
                        String nic=rs.getString("NIC");
                        String emptype=rs.getString("EMP_TYPE");
                    
                        String tbData[]={cID,name,emptype,tp,nic,email};
                        DefaultTableModel tblModel =(DefaultTableModel)jTable1.getModel(); 
                        tblModel.addRow(tbData);
                    }
                    btn_add.setEnabled(true); 
                    if(jTable1.getRowCount()!=0)
                            btn_edit.setEnabled(true);
                }
                if(jTable1.getRowCount()!=0)//check row count
                {
                    jTable1.setRowSelectionInterval(0, 0);
                    btn_remove.setEnabled(true);
                    lbl_empty.setVisible(false);
                }
                else{
                    btn_remove.setEnabled(false);
                    lbl_empty.setVisible(true);
                }
        }
        catch(Exception ex)//Is database has a problem, this catch stetment catch it
        {
            Logger.getLogger(FoodDetailsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        if(false){//validation
            
        }
        else{
            try {
                jLabel2.setText("Add New Stuff Member");
                btn_changeSave.setText("Add");
                jLabel8.setText("Password");
                jLabel9.setText("Confirm Password");
                clearform();
                panel_main.setVisible(false);
                Panel_AddEditStuff.setVisible(true);
                lbl_Error.setVisible(false);
                Emp obj=new Emp();
                txt_empID.setText(obj.newCID());
                checkbox_pwd_change.setSelected(true);
                btn_change_pwd.setVisible(false);
                checkbox_pwd_change.setVisible(false);
                btn_reset.setVisible(false);
                changePwdsection();
            } catch (Exception ex) {
                Logger.getLogger(SDDetailsPanel.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(new JFrame(), "Database error",
                            "Imformation", JOptionPane.ERROR_MESSAGE);
                panel_main.setVisible(true);
                Panel_AddEditStuff.setVisible(false);
            }
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void rdo_stuffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_stuffActionPerformed
        lbl_searchtitle.setText("Search by staff ID");
        btn_edit.setEnabled(true);
        viewALL();
        txt_search.setText("");
    }//GEN-LAST:event_rdo_stuffActionPerformed

    private void rdo_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_customerActionPerformed
        lbl_searchtitle.setText("Search by Customer Telephone Number");
        btn_edit.setEnabled(false);
        viewALL();
        txt_search.setText("");
    }//GEN-LAST:event_rdo_customerActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        lbl_Error.setVisible(false);
        lbl_empty.setVisible(false);
        //customer telephone number
        if (rdo_customer.isSelected() && txt_search.getText().isEmpty()) {
                lbl_Error.setVisible(true);
                lbl_Error.setText("Please enter a Customer telephone number");
        }
        else if(rdo_customer.isSelected() && "0100000001".equals(txt_search.getText())){
            clearTable();
            lbl_Error.setVisible(true);
            lbl_Error.setText("No results");
            btn_remove.setEnabled(false);
        }
        else if (rdo_customer.isSelected() && String.valueOf(txt_search.getText()).charAt(0) != '0') {//need to start with 0
            lbl_error.setText("Phone number must 07XXXXXXXX");
            lbl_error.setVisible(true);
        }
        else if(rdo_customer.isSelected() && txt_search.getText().matches("[0-9]+")==false)//if not only numbers
        {
            lbl_error.setText("Please enter a correct moblie number");
            lbl_error.setVisible(true);
        }
        else if(rdo_customer.isSelected() && txt_search.getText().length()!=10)//if more than 10 digits
        {
            lbl_error.setText("Please enter a correct moblie number");
            lbl_error.setVisible(true);
        }
        //if stuff member
        else if (rdo_stuff.isSelected() && txt_search.getText().isEmpty()) {
                lbl_Error.setVisible(true);
                lbl_Error.setText("Please enter a Employee ID");
        }
        else if (rdo_stuff.isSelected() && !txt_search.getText().matches("^(?i)EM\\d{3}$")) {//check the format
                lbl_Error.setVisible(true);
                lbl_Error.setText("Wrong Employee ID format");
        }
        else if (rdo_stuff.isSelected() && txt_search.getText().length()!=5) {
                lbl_Error.setVisible(true);
                lbl_Error.setText("Wrong Employee ID format");
        }
        else{
            try{
            clearTable();
            Connect obj = new Connect();
            Connection c = obj.getConnection();//Establish the connection
            cashier obj2=new cashier();
             //int q=1;System.out.println(q++); <- tester
                getDate obj1 =new getDate();
                String date=obj1.dateOnly();
                Statement stmt = c.createStatement();//Prepare statement
                ResultSet rs;
                //customer data
                if(rdo_customer.isSelected()){
                    //Change table header
                    JTableHeader th = jTable1.getTableHeader();
                    TableColumnModel tcm = th.getColumnModel();
                    TableColumn tc = tcm.getColumn(0);
                    tc.setHeaderValue( "Customer ID" );
                    th.repaint();
                    tc = tcm.getColumn(1);
                    tc.setHeaderValue( "Customer Name" );
                    th.repaint();
                    tc = tcm.getColumn(2);
                    tc.setHeaderValue( "Mobile number" );
                    th.repaint();
                    tc = tcm.getColumn(3);
                    tc.setHeaderValue( "Loyalty points");
                    th.repaint();
                    tc = tcm.getColumn(4);
                    tc.setHeaderValue( "Loyalty card" );
                    th.repaint();
                    //tc = tcm.getColumn(5);
                    //tc.setHeaderValue( "Email" );
                    //th.repaint();
                    //
                    rs = stmt.executeQuery("select * FROM CUSTOMER WHERE MOBILE_NUMBER='"+txt_search.getText()+"'");
                    while(rs.next()){
                        String cID=rs.getString("CUSTOMER_ID");
                        String fname=rs.getString("F_NAME");
                        String lname=rs.getString("L_NAME");
                        String tp=rs.getString("MOBILE_NUMBER");
                        String email=rs.getString("Email");
                        String points=rs.getString("POINTS");
                        String request="No";
                        if(rs.getInt("REQUEST")==1)
                            request="Requested";
                        else if(rs.getInt("REQUEST")==2)
                            request="Have";
                        String tbData[]={cID,fname+" "+lname,tp,points,request,email};
                        DefaultTableModel tblModel =(DefaultTableModel)jTable1.getModel(); 
                        tblModel.addRow(tbData);
                    }
                    btn_add.setEnabled(false); 
                }
                else{
                    //Change table header
                    JTableHeader th = jTable1.getTableHeader();
                    TableColumnModel tcm = th.getColumnModel();
                    TableColumn tc = tcm.getColumn(0);
                    tc.setHeaderValue( "Employee ID" );
                    th.repaint();
                    tc = tcm.getColumn(1);
                    tc.setHeaderValue( "Employee Name" );
                    th.repaint();
                    tc = tcm.getColumn(2);
                    tc.setHeaderValue( "Employee type" );
                    th.repaint();
                    tc = tcm.getColumn(3);
                    tc.setHeaderValue( "Mobile number");
                    th.repaint();
                    tc = tcm.getColumn(4);
                    tc.setHeaderValue( "NIC" );
                    th.repaint();
                    //tc = tcm.getColumn(5);
                    //tc.setHeaderValue( "Email" );
                    //th.repaint();
                    //
                    rs = stmt.executeQuery("select * FROM EMPLOYEE WHERE EMP_ID != 'EM001' AND EMP_ID='"+txt_search.getText()+"'");
                    while(rs.next()){
                        String cID=rs.getString("EMP_ID");
                        String name=rs.getString("F_NAME")+" "+rs.getString("L_NAME");
                        String tp=rs.getString("MOBILE_NUMBER");
                        String email=rs.getString("Email");
                        String nic=rs.getString("NIC");
                        String emptype=rs.getString("EMP_TYPE");
                    
                        String tbData[]={cID,name,emptype,tp,nic,email};
                        DefaultTableModel tblModel =(DefaultTableModel)jTable1.getModel(); 
                        tblModel.addRow(tbData);
                        if(jTable1.getRowCount()!=0)
                            btn_edit.setEnabled(true);
                    }
                    btn_add.setEnabled(true);
                }  
            if(jTable1.getRowCount()!=0)//check row count
            {
                jTable1.setRowSelectionInterval(0, 0);
                btn_remove.setEnabled(true); 
                
            }
            else{//if noone
                lbl_empty.setVisible(true);
                btn_remove.setEnabled(false);
                btn_edit.setEnabled(false);
            }
        }
        catch(Exception ex)//Is database has a problem, this catch stetment catch it
        {
            Logger.getLogger(FoodDetailsPanel.class.getName()).log(Level.SEVERE, null, ex);
            lbl_Error.setVisible(true);
            lbl_Error.setText("No result. Please check entered value");
        }
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        lbl_Error.setVisible(false);
        lbl_empty.setVisible(false);
        viewALL();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        lbl_Error.setVisible(false);
        clearTable();
        lbl_empty.setVisible(true);
        btn_remove.setEnabled(false);
        btn_edit.setEnabled(false);
        txt_search.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        lbl_Error.setVisible(false);
        int result = JOptionPane.showConfirmDialog((Component) null, "Are you sure?",
        "alert", JOptionPane.YES_NO_OPTION);
        System.out.println(result);
        if(result==0){
            try {
                int row=jTable1.getSelectedRow();
                String a=(String) jTable1.getValueAt(row, 0);
                if(rdo_customer.isSelected()){
                    Customer obj=new Customer();
                    boolean check=obj.removeCastomer(a);
                    if(!check){//unsuccessfully
                        JOptionPane.showMessageDialog(new JFrame(), "Customer has pending order! Unable to delete the customer",
                            "Imformation", JOptionPane.ERROR_MESSAGE);
                    }
                    else{//successfully deleted
                        JOptionPane.showMessageDialog(new JFrame(), "Delete successfull",
                            "Imformation", JOptionPane.INFORMATION_MESSAGE);
                        viewALL();
                        txt_search.setText("");
                    }
                }
                else{
                    Emp obj=new Emp();
                    obj.removeEmp(a);
                    viewALL();
                    JOptionPane.showMessageDialog(new JFrame(), "Delete successfull",
                            "Imformation", JOptionPane.INFORMATION_MESSAGE);
                }
                
            } catch (Exception ex) {
                Logger.getLogger(LoyaltyCardPanel.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(new JFrame(), "Database error",
               "Imformation", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_removeActionPerformed

    private void txt_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_searchMouseClicked
        lbl_Error.setVisible(false);
    }//GEN-LAST:event_txt_searchMouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        try {
            jLabel2.setText("Edit Stuff details");
            btn_changeSave.setText("Save Changes");
            jLabel8.setText("New Password");
            jLabel9.setText("Confirm New Password");
            panel_main.setVisible(false);
            Panel_AddEditStuff.setVisible(true);
            lbl_Error.setVisible(false);
            int row=jTable1.getSelectedRow();
            String a=(String) jTable1.getValueAt(row, 0);
            setForm(a);
            checkbox_pwd_change.setSelected(false);
            changePwdsection();
            btn_change_pwd.setVisible(true);
            checkbox_pwd_change.setVisible(true);
            btn_reset.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(SDDetailsPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JFrame(), "Database error",
                        "Imformation", JOptionPane.ERROR_MESSAGE);
           panel_main.setVisible(true);
            Panel_AddEditStuff.setVisible(false);
        }

    }//GEN-LAST:event_btn_editActionPerformed
    private void clearform(){
        txt_empID.setText("");
            txt_fname.setText("");
            txt_lname.setText("");
            txt_nic.setText("");
            txt_email.setText("");
            txt_tp.setText("");
            txt_newpwd.setText("");
            txt_newpwd_c.setText("");
            lbl_errorpwd.setVisible(false);
    }
    private void setForm(String eid) throws Exception{
        Emp obj=new Emp(eid);
        lbl_error.setVisible(false);
        lbl_errorpwd.setVisible(false);
        txt_empID.setText(obj.getEid());
        txt_fname.setText(obj.getFname());
        txt_lname.setText(obj.getLname());
        txt_nic.setText(obj.getNIC());
        txt_email.setText(obj.getEmail());
        switch(obj.getEtype()){
                case "CASHIER":
                    jComboBox_stufftype.setSelectedIndex(0);
                    break;
                case "CHEF":
                    jComboBox_stufftype.setSelectedIndex(1);
                    break;
            }
        txt_tp.setText("0"+Integer.toString(obj.getTp()));
        int item=0;System.out.println("aaaaaa "+obj.getEtype());
        if("CASHIER".equals(obj.getEtype()))
        {item=0;System.out.println("aaaaaa");}
        else
            item=1;
        jComboBox_stufftype.setSelectedIndex(item);
    }
    private void txt_newpwd_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_newpwd_cMouseClicked
        lbl_errorpwd.setText("");
    }//GEN-LAST:event_txt_newpwd_cMouseClicked

    private void checkbox_pwd_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_pwd_changeActionPerformed
        boolean check = checkbox_pwd_change.getModel().isSelected();
        txt_newpwd_c.setEnabled(check);
        txt_newpwd.setEnabled(check);
        btn_change_pwd.setEnabled(check);
    }//GEN-LAST:event_checkbox_pwd_changeActionPerformed
    private void changePwdsection(){
        boolean check = checkbox_pwd_change.getModel().isSelected();
        txt_newpwd_c.setEnabled(check);
        txt_newpwd.setEnabled(check);
        btn_change_pwd.setEnabled(check);
    }
    private void btn_change_pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_change_pwdActionPerformed
        try {
            lbl_errorpwd.setVisible(false);
            Emp obj1=new Emp();
            if(txt_newpwd.getText().equals("")){
                lbl_errorpwd.setText("Please enter the new password");
                lbl_errorpwd.setVisible(true);
                txt_newpwd.requestFocus();
            }
            else if(txt_newpwd_c.getText().equals("")){
                lbl_errorpwd.setText("Please Confirm your password");
                lbl_errorpwd.setVisible(true);
                txt_newpwd_c.requestFocus();
            }
            else if(txt_newpwd.getText().length()<6 && txt_newpwd.getText().length()<15){
                lbl_errorpwd.setText("Use 6 characters or more for your password");
                lbl_errorpwd.setVisible(true);
                txt_newpwd.requestFocus();
            }
            else if(!txt_newpwd_c.getText().equals(txt_newpwd.getText())){
                lbl_errorpwd.setText("Those passwords didn’t match. Try again.");
                lbl_errorpwd.setVisible(true);
                txt_newpwd_c.requestFocus();
                txt_newpwd_c.setText("");
            }
            else{
                obj1.setPwd(txt_empID.getText(),txt_newpwd.getText());
                checkbox_pwd_change.setSelected(false);
                boolean check = checkbox_pwd_change.getModel().isSelected();
                txt_newpwd_c.setEnabled(check);
                txt_newpwd.setEnabled(check);
                btn_change_pwd.setEnabled(check);
                txt_newpwd.setText("");
                txt_newpwd_c.setText("");
                JOptionPane.showMessageDialog(new JFrame(), "Passward changed",
                    "Imformation", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(ProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_change_pwdActionPerformed
    
    private void txt_newpwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_newpwdMouseClicked
        lbl_errorpwd.setText("");
    }//GEN-LAST:event_txt_newpwdMouseClicked

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        try {
            setForm(txt_empID.getText());
        } catch (Exception ex) {
            Logger.getLogger(SDDetailsPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JFrame(), "Database error",
                        "Imformation", JOptionPane.ERROR_MESSAGE);
           panel_main.setVisible(true);
            Panel_AddEditStuff.setVisible(false);
        }
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_changeSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changeSaveActionPerformed
        try {
            lbl_error.setVisible(false);
            lbl_errorpwd.setVisible(false);
            Emp obj2=new Emp();
            if(txt_fname.getText().length()==0){
                lbl_error.setText("Please enter the first name");
                lbl_error.setVisible(true);
                txt_fname.requestFocus();
            }
            else if(txt_fname.getText().length()<=2 || txt_fname.getText().length()>=15){//not allow 2>=length>=15
                lbl_error.setText("First name length should between 2 to 15");
                lbl_error.setVisible(true);
                txt_fname.requestFocus();
            }
            else if(!txt_fname.getText().matches("[a-zA-Z]+")){
                lbl_error.setText("First name can have only english letters");
                lbl_error.setVisible(true);
                txt_fname.requestFocus();
            }
            else if(txt_lname.getText().length()==0){
                lbl_error.setText("Please enter the last name");
                lbl_error.setVisible(true);
                txt_lname.requestFocus();
            }
            else if(txt_lname.getText().length()<=2 || txt_fname.getText().length()>=15){//not allow 2>=length>=15
                lbl_error.setText("Last name length should between 2 to 15");
                lbl_error.setVisible(true);
                txt_lname.requestFocus();
            }
            else if(!txt_lname.getText().matches("[a-zA-Z]+")){
                lbl_error.setText("Last name can have only english letters");
                lbl_error.setVisible(true);
                txt_lname.requestFocus();
            }
            else if(txt_email.getText().isEmpty()){//not allow 2>=length>=50
                lbl_error.setText("Please enter a email");
                lbl_error.setVisible(true);
                txt_email.requestFocus();
            }
            else if(txt_email.getText().length()>=50){//not allow 2>=length>=50
                lbl_error.setText("Last name length should between 2 to 15");
                lbl_error.setVisible(true);
                txt_email.requestFocus();
            }
            else if(!txt_email.getText().matches("[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}")){
                lbl_error.setText("Invalid email format");
                lbl_error.setVisible(true);
                txt_email.requestFocus();
            }
            else if (txt_nic.getText().length() != 10 && txt_nic.getText().length() != 12) {
                lbl_error.setText("Wrong NIC format");
                lbl_error.setVisible(true);
                txt_nic.requestFocus();
            }
            else if (!txt_nic.getText().matches("^\\d{9}[vVxX]|[12]\\d{11}$")) {
                lbl_error.setText("Wrong NIC format");
                lbl_error.setVisible(true);
                txt_nic.requestFocus();
            }
            else if("Add".equals(btn_changeSave.getText()) && obj2.isEmailAlreadyExist(txt_email.getText(),txt_empID.getText())){//
                lbl_error.setText("This email already use by a employee");
                lbl_error.setVisible(true);
                txt_nic.requestFocus();
            }
            else if(txt_tp.getText().isEmpty())//if empty
            {
                lbl_error.setText("Please enter your moblie number");
                lbl_error.setVisible(true);
                txt_tp.requestFocus();
            }
            else if("0100000001".equals(txt_tp.getText())){
                lbl_error.setVisible(true);
                lbl_error.setText("Please enter a correct moblie number");
                txt_tp.requestFocus();
            }
            else if (String.valueOf(txt_tp.getText()).charAt(0) != '0') {//need to start with 0
                lbl_error.setText("Phone number must 07XXXXXXXX format");
                lbl_error.setVisible(true);
                txt_tp.requestFocus();
            }
            else if(txt_tp.getText().matches("[0-9]+")==false)//if not only numbers
            {
                lbl_error.setText("Please enter a correct moblie number");
                lbl_error.setVisible(true);
                txt_tp.requestFocus();
            }
            else if(txt_tp.getText().length()!=10)//if more than 10 digits
            {
                lbl_error.setText("Please enter a correct moblie number");
                lbl_error.setVisible(true);
                txt_tp.requestFocus();
            }
            else if("Add".equals(btn_changeSave.getText()) && txt_newpwd.getText().equals("")){
                lbl_errorpwd.setVisible(true);
                lbl_errorpwd.setText("Please enter the new password");
                txt_newpwd.requestFocus();
            }
            else if("Add".equals(btn_changeSave.getText()) && txt_newpwd_c.getText().equals("")){
                lbl_errorpwd.setVisible(true);
                lbl_errorpwd.setText("Please Confirm your password");
                txt_newpwd_c.requestFocus();
            }
            else if("Add".equals(btn_changeSave.getText()) && !txt_newpwd_c.getText().equals(txt_newpwd.getText())){
                lbl_errorpwd.setVisible(true);
                lbl_errorpwd.setText("Those passwords didn’t match. Try again.");
                txt_newpwd_c.requestFocus();
            }
            else if("Add".equals(btn_changeSave.getText()) && txt_newpwd.getText().length()<6 && txt_newpwd.getText().length()<15){
                lbl_errorpwd.setVisible(true);
                lbl_errorpwd.setText("Use 6 characters or more for your password");
                txt_newpwd.requestFocus();
            }
            else{
                if("Save Changes".equals(btn_changeSave.getText())){
                    try {
                        String emp_type="";
                        if(jComboBox_stufftype.getSelectedIndex()==0)
                            emp_type="CASHIER";
                        else
                            emp_type="CHEF";
                        obj2.setEmpDetails(txt_empID.getText(),txt_fname.getText(),txt_lname.getText(),txt_email.getText(),txt_tp.getText(),txt_nic.getText(),emp_type);
                        JOptionPane.showMessageDialog(new JFrame(), "Details successfully changed",
                                "Imformation", JOptionPane.INFORMATION_MESSAGE);
                        clearform();
                        panel_main.setVisible(true);
                        Panel_AddEditStuff.setVisible(false);
                        lbl_Error.setVisible(false);
                        viewALL();
                    } catch (Exception ex) {
                        Logger.getLogger(ProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else if("Add".equals(btn_changeSave.getText())){
                    String emp_type="";
                    if(jComboBox_stufftype.getSelectedIndex()==0)
                        emp_type="CASHIER";
                    else
                        emp_type="CHEF";
                    try {
                        obj2.addStaff(txt_empID.getText(),txt_fname.getText(),txt_lname.getText(),txt_tp.getText(),txt_email.getText(),txt_nic.getText(),emp_type,txt_nic.getText());
                        clearform();
                        JOptionPane.showMessageDialog(new JFrame(), "New staff member added",
                            "Imformation", JOptionPane.INFORMATION_MESSAGE);
                        panel_main.setVisible(true);
                        Panel_AddEditStuff.setVisible(false);
                        lbl_Error.setVisible(false);
                        viewALL();
                    } catch (Exception ex) {
                        Logger.getLogger(SDDetailsPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
            }
        } catch (Exception ex) {            
            Logger.getLogger(SDDetailsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_changeSaveActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        lbl_error.setVisible(false);
        lbl_errorpwd.setVisible(false);
        clearform();
        panel_main.setVisible(true);
        Panel_AddEditStuff.setVisible(false);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void jComboBox_stufftypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_stufftypeActionPerformed
        
    }//GEN-LAST:event_jComboBox_stufftypeActionPerformed
    
    private void clearTable(){
        DefaultTableModel tblModel =(DefaultTableModel)jTable1.getModel(); 
        int rowCount = tblModel.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            tblModel.removeRow(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_AddEditStuff;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_changeSave;
    private javax.swing.JButton btn_change_pwd;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_search;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkbox_pwd_change;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox_stufftype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_Error;
    private javax.swing.JLabel lbl_empty;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_errorpwd;
    private javax.swing.JLabel lbl_searchtitle;
    private javax.swing.JPanel panel_main;
    private javax.swing.JRadioButton rdo_customer;
    private javax.swing.JRadioButton rdo_stuff;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_empID;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JPasswordField txt_newpwd;
    private javax.swing.JPasswordField txt_newpwd_c;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_tp;
    // End of variables declaration//GEN-END:variables
}
