/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Cashier;
import Customer.GetTpPage;
import Customer.LoginPage;
import DBconnection.mgrDashboard;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Gimhan
 */
public class CashierMain extends javax.swing.JFrame {
    /** Creates new form CashierDashboard */
    String cashierID="EM002";
    public CashierMain() {
        initComponents();
        //getData();
    }
    public CashierMain(String cashierID) {
        this.cashierID=cashierID;
        initComponents();
        //getData();
    }
    
    public void getData(){
        try {
            mgrDashboard obj1= new mgrDashboard();
            //lbl_income.setText(Integer.toString(obj1.todayIncome())+".00");
            
        } catch (Exception ex) {
            Logger.getLogger(CashierMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nav_panel = new javax.swing.JPanel();
        lbl_heading = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        btn_Dashboard = new javax.swing.JButton();
        btn_reports = new javax.swing.JButton();
        btn_sd_details = new javax.swing.JButton();
        btn_foodDetails = new javax.swing.JButton();
        btn_loyaltyCards = new javax.swing.JButton();
        btn_profile = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        cashierDashboard1 = new Cashier.cashierDashboard();
        issueLoyaltyCard1 = new Cashier.IssueLoyaltyCard();
        jPanel1 = new javax.swing.JPanel();
        lbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nav_panel.setBackground(new java.awt.Color(173, 85, 2));

        lbl_heading.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lbl_heading.setForeground(new java.awt.Color(255, 255, 255));
        lbl_heading.setText("Coffe Shop");

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo rounded resized.png"))); // NOI18N

        btn_Dashboard.setBackground(new java.awt.Color(252, 152, 3));
        btn_Dashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        btn_Dashboard.setText("Dashboard");
        btn_Dashboard.setBorderPainted(false);
        btn_Dashboard.setContentAreaFilled(false);
        btn_Dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Dashboard.setOpaque(true);
        btn_Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_DashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_DashboardMousePressed(evt);
            }
        });
        btn_Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DashboardActionPerformed(evt);
            }
        });

        btn_reports.setBackground(new java.awt.Color(173, 85, 2));
        btn_reports.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_reports.setForeground(new java.awt.Color(255, 255, 255));
        btn_reports.setText("New Order");
        btn_reports.setBorderPainted(false);
        btn_reports.setContentAreaFilled(false);
        btn_reports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reports.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btn_reports.setOpaque(true);
        btn_reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_reportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_reportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_reportsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_reportsMousePressed(evt);
            }
        });
        btn_reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportsActionPerformed(evt);
            }
        });

        btn_sd_details.setBackground(new java.awt.Color(173, 85, 2));
        btn_sd_details.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_sd_details.setForeground(new java.awt.Color(255, 255, 255));
        btn_sd_details.setText("View Customer Details");
        btn_sd_details.setBorderPainted(false);
        btn_sd_details.setContentAreaFilled(false);
        btn_sd_details.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sd_details.setMargin(new java.awt.Insets(0, 14, 2, 14));
        btn_sd_details.setOpaque(true);
        btn_sd_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sd_detailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_sd_detailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_sd_detailsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_sd_detailsMousePressed(evt);
            }
        });
        btn_sd_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sd_detailsActionPerformed(evt);
            }
        });

        btn_foodDetails.setBackground(new java.awt.Color(173, 85, 2));
        btn_foodDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_foodDetails.setForeground(new java.awt.Color(255, 255, 255));
        btn_foodDetails.setText("Food Details");
        btn_foodDetails.setBorderPainted(false);
        btn_foodDetails.setContentAreaFilled(false);
        btn_foodDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_foodDetails.setOpaque(true);
        btn_foodDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_foodDetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_foodDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_foodDetailsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_foodDetailsMousePressed(evt);
            }
        });
        btn_foodDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_foodDetailsActionPerformed(evt);
            }
        });

        btn_loyaltyCards.setBackground(new java.awt.Color(173, 85, 2));
        btn_loyaltyCards.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_loyaltyCards.setForeground(new java.awt.Color(255, 255, 255));
        btn_loyaltyCards.setText("Issue Loyalty Cards");
        btn_loyaltyCards.setBorderPainted(false);
        btn_loyaltyCards.setContentAreaFilled(false);
        btn_loyaltyCards.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_loyaltyCards.setOpaque(true);
        btn_loyaltyCards.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loyaltyCardsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_loyaltyCardsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_loyaltyCardsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_loyaltyCardsMousePressed(evt);
            }
        });
        btn_loyaltyCards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loyaltyCardsActionPerformed(evt);
            }
        });

        btn_profile.setBackground(new java.awt.Color(173, 85, 2));
        btn_profile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_profile.setForeground(new java.awt.Color(255, 255, 255));
        btn_profile.setText("------");
        btn_profile.setBorderPainted(false);
        btn_profile.setContentAreaFilled(false);
        btn_profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_profile.setOpaque(true);
        btn_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_profileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_profileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_profileMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_profileMousePressed(evt);
            }
        });
        btn_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profileActionPerformed(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(173, 85, 2));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Log Out");
        btn_logout.setBorderPainted(false);
        btn_logout.setContentAreaFilled(false);
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.setOpaque(true);
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_logoutMousePressed(evt);
            }
        });
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Nav_panelLayout = new javax.swing.GroupLayout(Nav_panel);
        Nav_panel.setLayout(Nav_panelLayout);
        Nav_panelLayout.setHorizontalGroup(
            Nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Dashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_reports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_sd_details, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(btn_profile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_foodDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_loyaltyCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Nav_panelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_heading)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Nav_panelLayout.setVerticalGroup(
            Nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Nav_panelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(Nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Nav_panelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbl_heading)))
                .addGap(43, 43, 43)
                .addComponent(btn_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_reports, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_sd_details, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_foodDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_loyaltyCards, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        getContentPane().add(Nav_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 740));

        jTabbedPane1.addTab("tab2", cashierDashboard1);
        jTabbedPane1.addTab("tab2", issueLoyaltyCard1);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab1", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, -40, 1090, 760));

        lbl_background.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DashboardMouseClicked
        // TODO add your handling code here:
        btn_Dashboard.setBackground(new java.awt.Color(252, 152, 3));
        btn_reports.setBackground(new java.awt.Color(173,85,2));
        btn_sd_details.setBackground(new java.awt.Color(173,85,2));
        btn_foodDetails.setBackground(new java.awt.Color(173,85,2));
        btn_loyaltyCards.setBackground(new java.awt.Color(173,85,2));
        btn_profile.setBackground(new java.awt.Color(173,85,2));
        btn_logout.setBackground(new java.awt.Color(173,85,2));
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btn_DashboardMouseClicked

    private void btn_DashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DashboardMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DashboardMouseEntered

    private void btn_DashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DashboardMouseExited
        // TODO add your handling code here:[173,85,2]
    }//GEN-LAST:event_btn_DashboardMouseExited

    private void btn_DashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DashboardMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DashboardMousePressed

    private void btn_DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DashboardActionPerformed

    private void btn_reportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportsMouseClicked
        GetTpPage obj=new GetTpPage(cashierID);
        obj.show();
        dispose();
        /*
        btn_Dashboard.setBackground(new java.awt.Color(173,85,2));
        btn_reports.setBackground(new java.awt.Color(252, 152, 3));
        btn_sd_details.setBackground(new java.awt.Color(173,85,2));
        btn_foodDetails.setBackground(new java.awt.Color(173,85,2));
        btn_loyaltyCards.setBackground(new java.awt.Color(173,85,2));
        btn_profile.setBackground(new java.awt.Color(173,85,2));
        btn_logout.setBackground(new java.awt.Color(173,85,2));
        jTabbedPane.setSelectedIndex(1);
        */
    }//GEN-LAST:event_btn_reportsMouseClicked

    private void btn_reportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reportsMouseEntered

    private void btn_reportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reportsMouseExited

    private void btn_reportsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportsMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reportsMousePressed

    private void btn_reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reportsActionPerformed

    private void btn_sd_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sd_detailsMouseClicked
        // TODO add your handling code here:
        //jTabbedPane.setSelectedIndex(2);
        btn_Dashboard.setBackground(new java.awt.Color(173,85,2));
        btn_reports.setBackground(new java.awt.Color(173,85,2));
        btn_sd_details.setBackground(new java.awt.Color(252, 152, 3));
        btn_foodDetails.setBackground(new java.awt.Color(173,85,2));
        btn_loyaltyCards.setBackground(new java.awt.Color(173,85,2));
        btn_profile.setBackground(new java.awt.Color(173,85,2));
        btn_logout.setBackground(new java.awt.Color(173,85,2));
    }//GEN-LAST:event_btn_sd_detailsMouseClicked

    private void btn_sd_detailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sd_detailsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sd_detailsMouseEntered

    private void btn_sd_detailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sd_detailsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sd_detailsMouseExited

    private void btn_sd_detailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sd_detailsMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sd_detailsMousePressed

    private void btn_sd_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sd_detailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sd_detailsActionPerformed

    private void btn_foodDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_foodDetailsMouseClicked
        btn_Dashboard.setBackground(new java.awt.Color(173,85,2));
        btn_reports.setBackground(new java.awt.Color(173,85,2));
        btn_sd_details.setBackground(new java.awt.Color(173,85,2));
        btn_foodDetails.setBackground(new java.awt.Color(252, 152, 3));
        btn_loyaltyCards.setBackground(new java.awt.Color(173,85,2));
        btn_profile.setBackground(new java.awt.Color(173,85,2));
        btn_logout.setBackground(new java.awt.Color(173,85,2));
    }//GEN-LAST:event_btn_foodDetailsMouseClicked

    private void btn_foodDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_foodDetailsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_foodDetailsMouseEntered

    private void btn_foodDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_foodDetailsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_foodDetailsMouseExited

    private void btn_foodDetailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_foodDetailsMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_foodDetailsMousePressed

    private void btn_foodDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_foodDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_foodDetailsActionPerformed

    private void btn_loyaltyCardsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loyaltyCardsMouseClicked
        btn_Dashboard.setBackground(new java.awt.Color(173,85,2));
        btn_reports.setBackground(new java.awt.Color(173,85,2));
        btn_sd_details.setBackground(new java.awt.Color(173,85,2));
        btn_foodDetails.setBackground(new java.awt.Color(173,85,2));
        btn_loyaltyCards.setBackground(new java.awt.Color(252, 152, 3));
        btn_profile.setBackground(new java.awt.Color(173,85,2));
        btn_logout.setBackground(new java.awt.Color(173,85,2));
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btn_loyaltyCardsMouseClicked

    private void btn_loyaltyCardsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loyaltyCardsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loyaltyCardsMouseEntered

    private void btn_loyaltyCardsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loyaltyCardsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loyaltyCardsMouseExited

    private void btn_loyaltyCardsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loyaltyCardsMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loyaltyCardsMousePressed

    private void btn_loyaltyCardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loyaltyCardsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loyaltyCardsActionPerformed

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        btn_Dashboard.setBackground(new java.awt.Color(173,85,2));
        btn_reports.setBackground(new java.awt.Color(173,85,2));
        btn_sd_details.setBackground(new java.awt.Color(173,85,2));
        btn_foodDetails.setBackground(new java.awt.Color(173,85,2));
        btn_loyaltyCards.setBackground(new java.awt.Color(173,85,2));
        btn_profile.setBackground(new java.awt.Color(173,85,2));
        btn_logout.setBackground(new java.awt.Color(252, 152, 3));
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logoutMousePressed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        LoginPage obj=new LoginPage();
        obj.show();
        dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed
    
    public void closeCashier(){
        dispose();
    }
    private void btn_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_profileActionPerformed

    private void btn_profileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_profileMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_profileMousePressed

    private void btn_profileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_profileMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_profileMouseExited

    private void btn_profileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_profileMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_profileMouseEntered

    private void btn_profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_profileMouseClicked
        btn_Dashboard.setBackground(new java.awt.Color(173,85,2));
        btn_reports.setBackground(new java.awt.Color(173,85,2));
        btn_sd_details.setBackground(new java.awt.Color(173,85,2));
        btn_foodDetails.setBackground(new java.awt.Color(173,85,2));
        btn_loyaltyCards.setBackground(new java.awt.Color(173,85,2));
        btn_profile.setBackground(new java.awt.Color(252, 152, 3));
        btn_logout.setBackground(new java.awt.Color(173,85,2));
    }//GEN-LAST:event_btn_profileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Nav_panel;
    private javax.swing.JButton btn_Dashboard;
    private javax.swing.JButton btn_foodDetails;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_loyaltyCards;
    private javax.swing.JButton btn_profile;
    private javax.swing.JButton btn_reports;
    private javax.swing.JButton btn_sd_details;
    private Cashier.cashierDashboard cashierDashboard1;
    private Cashier.IssueLoyaltyCard issueLoyaltyCard1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_heading;
    // End of variables declaration//GEN-END:variables

}
