/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Cashier;

/**
 *
 * @author Gimhan
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_income = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_delivered = new javax.swing.JLabel();
        lbl_pendingOdr = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_refresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_dBoard = new javax.swing.JTable();
        btn_viewtheOdr = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_completeOdr = new javax.swing.JButton();
        btn_hold = new javax.swing.JButton();
        lbl_background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel1.setText("Today Imcome");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        lbl_income.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lbl_income.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_income.setText("0.00");
        add(lbl_income, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel2.setText("Pending Order count");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        lbl_delivered.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lbl_delivered.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_delivered.setText("0");
        add(lbl_delivered, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 30, -1));

        lbl_pendingOdr.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lbl_pendingOdr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_pendingOdr.setText("0");
        add(lbl_pendingOdr, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 30, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel5.setText("Delivered orders");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, -1));

        btn_refresh.setText("Refresh");
        add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 60, -1, -1));

        jTable_dBoard.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jTable_dBoard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Customer name", "Order type", "Status", "Ordered Time", "Tables"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_dBoard.setRowHeight(28);
        jScrollPane1.setViewportView(jTable_dBoard);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 1050, -1));

        btn_viewtheOdr.setText("View The Order");
        add(btn_viewtheOdr, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, 140, 40));

        btn_cancel.setText("Cancel the order");
        add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 660, 160, 40));

        btn_completeOdr.setText("Complete the order");
        add(btn_completeOdr, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 650, 180, 50));

        btn_hold.setText("Hold");
        add(btn_hold, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 660, 110, 40));
        add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 740));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_completeOdr;
    private javax.swing.JButton btn_hold;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_viewtheOdr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_dBoard;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_delivered;
    private javax.swing.JLabel lbl_income;
    private javax.swing.JLabel lbl_pendingOdr;
    // End of variables declaration//GEN-END:variables
}
